import type { Metadata } from "next";
import "@/styles/index.css";
import { inter, open_sans, poppins } from "@/config/font";
import { cn } from "@/utils";

export const metadata: Metadata = {
  title: "Bizconnect24",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(inter.variable, poppins.variable, open_sans.variable)}
      >
        {children}
      </body>
    </html>
  );
}
