import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Bizconnect24",
  description: "Generated by create next app",
};

export default function Home() {
  return <main className="p-6"></main>;
}
