name: React CI

on:
  push:
    branches:
      - "dev"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.15.1]

    steps:
      - uses: actions/checkout@v1 # This step checks out your repository
      - name: Setup Symfony
        working-directory: ./client
        run: |
          touch .env 
          echo DATABASE_URL=${{secrets.BACKEND_URL}} >> .env
          yarn install
          yarn build

      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ca-central-1"
          SOURCE_DIR: "./client/dist" # optional: defaults to entire repository
